package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, March 20, 2023 12:22:41 AM CDT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
