package Restaurant;


/**
* Restaurant/RestC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaProject.idl
* Friday, March 24, 2023 4:12:59 PM CDT
*/

public interface RestC extends RestCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RestC
