package Restaurant;


/**
* Restaurant/RestCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaProject.idl
* Friday, March 24, 2023 4:12:59 PM CDT
*/

public interface RestCOperations 
{
  String sayHello ();
  String Menu ();
  String OrderFood (String user, int friedchicken, int cola, float money);
  String customerOrder (String user);
  String viewcurrentorders ();
} // interface RestCOperations
