package Restaurant;

/**
* Restaurant/RestCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaProject.idl
* Friday, March 24, 2023 4:12:59 PM CDT
*/

public final class RestCHolder implements org.omg.CORBA.portable.Streamable
{
  public Restaurant.RestC value = null;

  public RestCHolder ()
  {
  }

  public RestCHolder (Restaurant.RestC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Restaurant.RestCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Restaurant.RestCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Restaurant.RestCHelper.type ();
  }

}
